name: ecommerce_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  shared_preferences: ^2.0.15
  tab_indicator_styler: ^2.0.0
  flutter_rating_bar: ^4.0.1
  numeral: ^2.0.1
  flutter_colorpicker: ^1.0.3
  font_awesome_flutter: ^10.1.0
  country_list_pick: ^1.0.1+5
  flutter_svg: ^1.1.0
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  firebase_dynamic_links: ^4.2.5
  cloud_firestore: ^3.1.17
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Bilbo-Regular
      fonts: 
        - asset: font/Bilbo-Regular.ttf
    - family: Actonia PERSONAL
      fonts:
        - asset: font/Actonia_PERSONAL.ttf

