name: ecommerce_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  shared_preferences: ^2.0.15
  tab_indicator_styler: ^2.0.0
  flutter_rating_bar: ^4.0.1
  numeral: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Bilbo-Regular
      fonts: 
        - asset: font/Bilbo-Regular.ttf

